name: materials-example
channels:
  - conda-forge
dependencies:
  - ipympl
  - ipywidgets
  - jupyterlab=2
  - matplotlib
  - nbresuse
  - numpy
  - pandas
  - python=3
  - psutil
  - click
  - curl
  - cycler
  - decorator
  - defusedxml
  - futures
  - gdal
  - geos
  - gettext
  - giflib
  - glib
  - h5py
  - hdf5
  - markupsafe
  - matplotlib
  - mistune
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - pexpect
  - pickleshare
  - pip
  - pixman
  - poppler
  - proj4
  - ptyprocess
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - six
  - sqlite
  - pip:
    - altgraph
    - asn1crypto
    - asteval
    - cffi
    - cftime
    - chardet
    - cryptography
    - dis3
    - dndclib
    - fiona
    - future
    - geojson
    - ipaddress
    - lmfit
    - macholib
    - netcdf4
    - pyshp
    - pysolar
    - requests
    - scikit-learn
    - scipy
    - shapely
    - simpledbf
    - sklearn
    - statsmodels
    - twilio
    - uncertainties
    - urllib3
    - xlrd
