name: DNDC
channels:
  - conda-forge
dependencies:
  - ipympl
  - ipywidgets
  - jupyterlab=2
  - matplotlib
  - nbresuse
  - numpy
  - pandas
  - python=3
  - click
  - gdal
  - proj4
  - pip:
    - dndclib
    - fiona
    - geojson
    - lmfit
    - netcdf4
    - pyshp
    - pysolar
    - requests
    - scikit-learn
    - scipy
    - shapely
    - simpledbf
    - sklearn
    - statsmodels
    - twilio
    - xlrd
    - h5py
    - matplotlib
